### ISSUE TITLE
会有某一个折线label饼图外丢失的问题

### ISSUE THREAD

**Issue by LucasXu01** [huzipiaopiao/MPAndroidChartFix#1]
![image](https://user-images.githubusercontent.com/26033338/45210622-abc4c880-b2c2-11e8-9f2c-52f5cd4964b0.png)

**Comment by LucasXu01** [comment]
开源很有帮助，这个问题不知为何，继续添加数据后会这个问题会消失，但是再次添加又时常出现这个丢失问题。

**Comment by LucasXu01** [comment]
hi,经过多次测试，当左侧只有一个数据的时候，会发生这种label消失的问题！当左侧数据大于一个时候，会都显示出来！

**Comment by huzipiaopiao** [comment]
V1.0.3中以及修改这个问题，如果有时间，可以再试下，谢谢你的测试
