### ISSUE TITLE
值重叠问题解决，线条颜色根据饼图颜色设置功能失效

### ISSUE THREAD

**Issue by zxdeer** [huzipiaopiao/MPAndroidChartFix#3]
之前官方提供的线条颜色根据饼图颜色设置的功能失效了

**Comment by zxdeer** [comment]
解决了

**Comment by huzipiaopiao** [comment]
不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？

**Comment by zxdeer** [comment]
> 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？

![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)

**Comment by huzipiaopiao** [comment]
> > 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？
> 
> ![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)

明白了，我是用的v3.0.3的MPAndroidChart，当时他们还没有提供这个方法，所以只能通过setValueLineColor()设置，高版本的可以通过你的方案实现:thumbsup:

**Comment by zxdeer** [comment]
> > > 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)
> 
> 明白了，我是用的v3.0.3的MPAndroidChart，当时他们还没有提供这个方法，所以只能通过setValueLineColor()设置，高版本的可以通过你的方案实现👍

你饼图先动画后画折线，这个位置错乱你咋解决的啊

**Comment by huzipiaopiao** [comment]
> > > > 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)
> > 
> > 
> > 明白了，我是用的v3.0.3的MPAndroidChart，当时他们还没有提供这个方法，所以只能通过setValueLineColor()设置，高版本的可以通过你的方案实现👍
> 
> 你饼图先动画后画折线，这个位置错乱你咋解决的啊

不好意思，没听懂你的问题，是说折线位置错乱吗？

**Comment by zxdeer** [comment]
> > > > > 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)
> > > 
> > > 
> > > 明白了，我是用的v3.0.3的MPAndroidChart，当时他们还没有提供这个方法，所以只能通过setValueLineColor()设置，高版本的可以通过你的方案实现👍
> > 
> > 
> > 你饼图先动画后画折线，这个位置错乱你咋解决的啊
> 
> 不好意思，没听懂你的问题，是说折线位置错乱吗？

是的，感觉线很乱

**Comment by huzipiaopiao** [comment]
> > > > > > 不好意思，我找了一下，没找自动根据饼图颜色设置线条颜色的方法；只找到了setValueLineColor()这个方法，方便说下你是用的哪个方法吗？
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/4919430/70028438-9cc0e900-15df-11ea-9563-a2f90d1fee64.png)
> > > > 
> > > > 
> > > > 明白了，我是用的v3.0.3的MPAndroidChart，当时他们还没有提供这个方法，所以只能通过setValueLineColor()设置，高版本的可以通过你的方案实现👍
> > > 
> > > 
> > > 你饼图先动画后画折线，这个位置错乱你咋解决的啊
> > 
> > 
> > 不好意思，没听懂你的问题，是说折线位置错乱吗？
> 
> 是的，感觉线很乱

暂时，没有解决这个，数据少的时候，看起来确实没有他们官方的那么好看
